name: build
permissions: {}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  schedule:
  - cron: '0 10 * * 1' # run at 10am on Monday

  workflow_call:
    inputs:
      skipTests:
        description: 'Skip tests, useful when there is a dedicated CI job for tests'
        default: false
        type: boolean

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true

      - name: Format code
        run: gofmt -s -w . && git diff --exit-code

      - name: Vet code
        run: go vet ./...

      - name: Tidy code
        run: go mod tidy && git diff --exit-code

      - name: Download and Verify dependencies
        run: go mod download && go mod verify

      - name: Code generation
        run: go generate ./... && git diff --exit-code

      - name: Build code
        run: go build -trimpath -o /dev/null ./...

      - name: Compile tests
        if: ${{ inputs.skipTests }}
        run: go test -exec /bin/true ./...

      - name: Run tests
        if: ${{ !inputs.skipTests }}
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.out ./...

      - name: Check Benchmarks
        if: ${{ !inputs.skipTests }}
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...

      - name: Upload Coverage
        if: ${{ !inputs.skipTests }}
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.out
          fail_ci_if_error: false
